### ISSUE TITLE
 United Water(Suez) J085 WSL/Restro for QA

### ISSUE THREAD

**Issue by ghost** [AditiRangdal/HSUSA-QA-Support-Task#1]
Hi @prdxn,
Hope all is well. We have a new Water Service Line product that needs to be QA'd. Here is the path to the QA doc, Product standard and import sheet: http://bit.ly/2Q8YYjV
Any questions let me know.
Thanks for your help!
Amrin

**Comment by AditiRangdal** [comment]
Hii Amrin,
Below is the timeline for product **United Water(Suez) J085 WSL/Restro**
**Start Date** - 9/25/2018
**End Date** - 9/26/2018
Thanks!

**Comment by AditiRangdal** [comment]
Hi Amrin,
QA of **United Water(Suez) J085 WSL/Restro Product** is completed.
**Here is the path to the Docs send by you:** http://bit.ly/2Q8YYjV
**Here is the path to the QA Docs:** https://is.gd/FGv17H
Thanks!
